export const LEGAL_VERSION = "2026-09-26";
export const SELLER = {
  name: "AKIN MOTOSİKLET (UTKU BAHA AKIN)",
  address: "32 EVLER MAHALLESİ SAHİ GÜVEN SOKAK NO 10/A SERDİVAN / SAKARYA",
  email: "bahadir_akin@hotmail.com",
  phone: "0542 154 5403",
  taxOffice: "Gümrükönü Vergi Dairesi",
  taxNumber: "0270652823",
  kep: "utkubaha.akin@hs09.kep.tr",
};
export const legalDocuments = {
  "on-bilgilendirme": { title: "Ön Bilgilendirme Formu", body: `Satıcı: ${SELLER.name}\nAdres: ${SELLER.address}\nE-posta: ${SELLER.email}\nTelefon: ${SELLER.phone}\n\nSipariş verilmeden önce ürünlerin temel nitelikleri, vergiler dahil fiyatı, varsa indirimler, kargo/teslim masrafları, ödeme yöntemi ve sipariş toplamı ödeme ekranında gösterilir. Teslimat, siparişte belirtilen adrese yapılır. Tüketici, kanuni istisnalar saklı kalmak üzere mesafeli satışlarda cayma hakkına sahiptir. Cayma ve iade koşulları ayrıca yayımlanır. Uyuşmazlıklarda yürürlükteki tüketici mevzuatındaki başvuru yolları kullanılabilir.` },
  "mesafeli-satis": { title: "Mesafeli Satış Sözleşmesi", body: `SATICI\n${SELLER.name}\n${SELLER.address}\n${SELLER.email} · ${SELLER.phone}\n\nALICI\nSipariş sırasında beyan edilen kişi ve iletişim bilgileridir.\n\nKONU\nBu sözleşme, internet sitesi üzerinden tüketici sıfatıyla verilen siparişlerde ürünlerin satışı ve teslimine ilişkin tarafların hak ve yükümlülüklerini düzenler. Siparişe özgü ürün, adet, fiyat, KDV, indirim, kargo, ödeme ve teslimat bilgileri sipariş kaydının ayrılmaz parçasıdır.\n\nTESLİMAT VE ÖDEME\nÖdeme, ödeme ekranında seçilen yöntemle yapılır. Ürünler yasal süreler ve siparişte belirtilen teslimat koşulları çerçevesinde gönderilir.\n\nCAYMA VE İADE\nTüketicinin cayma hakkı ve istisnaları 6502 sayılı Kanun ve Mesafeli Sözleşmeler Yönetmeliği çerçevesinde uygulanır. Cayma hakkının kullanımı için satıcıya açık bir bildirim yapılması gerekir. Niteliği gereği iadesi uygun olmayan veya mevzuatta cayma hakkı dışında bırakılan ürün/hizmetler bakımından yasal istisnalar uygulanır.\n\nUYUŞMAZLIK\nTüketici, yürürlükteki parasal sınırlar ve görev kuralları çerçevesinde tüketici hakem heyetlerine veya tüketici mahkemelerine başvurabilir.` },
  "cayma-iade": { title: "Cayma, İptal ve İade Koşulları", body: `Tüketici siparişlerinde cayma hakkı, 6502 sayılı Kanun ve Mesafeli Sözleşmeler Yönetmeliği kapsamında uygulanır. Cayma bildirimi ${SELLER.email} adresine veya satıcının iletişim kanallarına açık bir beyanla iletilebilir. Ürün, mevzuatta öngörülen süre ve koşullara uygun şekilde iade edilmelidir. Cayma hakkının istisnaları ile ayıplı mala ilişkin tüketici hakları saklıdır. Sipariş iptali, siparişin hazırlık/kargo durumuna göre sistem üzerinden veya satıcıyla iletişim kurularak talep edilebilir.` },
  "kvkk": { title: "KVKK Aydınlatma Metni", body: `Veri sorumlusu: ${SELLER.name}. Sipariş, üyelik, teslimat, faturalama, müşteri hizmetleri, tahsilat, güvenlik ve yasal yükümlülüklerin yerine getirilmesi amaçlarıyla kimlik, iletişim, adres, sipariş, işlem ve fatura bilgileri işlenebilir. Veriler; ödeme, kargo, bilişim, muhasebe ve yetkili kamu kurumları gibi hizmetin gerektirdiği alıcı gruplarına, ilgili hukuki şartların bulunması halinde aktarılabilir. Veriler elektronik ortamda doğrudan ilgili kişiden ve işlem kayıtlarından elde edilir. İşleme faaliyetleri KVKK'daki sözleşmenin kurulması/ifası, hukuki yükümlülük, hakkın tesisi-kullanılması-korunması ve meşru menfaat gibi uygulanabilir hukuki sebeplere dayanır. KVKK'nın 11. maddesi kapsamındaki haklarınıza ilişkin başvurularınızı ${SELLER.email} üzerinden iletebilirsiniz. Aydınlatma, pazarlama izni veya açık rıza anlamına gelmez.` },
  "bayi-satis-kosullari": { title: "Bayi / B2B Satış ve Sipariş Koşulları", body: `Bu koşullar onaylı bayi hesabıyla ticari amaçla verilen siparişlere uygulanır. Satıcı ${SELLER.name}'dir. Ürün, adet, ticari fiyat/iskonto, KDV, kargo, ödeme ve teslimat bilgileri sipariş anındaki kayıtla belirlenir. Bayi, sipariş verdiği ürünlerin kendi ticari faaliyeti kapsamında alındığını kabul eder. Tüketicilere özgü cayma hükümleri, işlemin niteliğine göre ticari alımlara uygulanmayabilir. Ayıp, teslimat, iade, ödeme ve diğer konularda emredici mevzuat hükümleri saklıdır.` },
  "cari-kart-tahsilat": { title: "Cari Hesap Kart Tahsilatı Bilgilendirmesi", body: `Bu işlem ürün siparişi değildir; onaylı bayi hesabındaki cari borca mahsup edilmek üzere kartla tahsilat işlemidir. Girilen tutar ödeme kuruluşu tarafından başarılı olarak doğrulandıktan sonra cari hesaba tahsilat olarak işlenir. Borçtan fazla ödeme yapılması halinde fark cari hesapta alacak bakiyesi oluşturabilir. Başarısız veya iptal edilmiş kart işlemi cari bakiyeyi değiştirmez. Kart bilgileri AKN Motosiklet tarafından doğrudan saklanmaz; ödeme işlemi kullanılan ödeme hizmeti sağlayıcısının güvenli ödeme altyapısında yürütülür.` },
} as const;
export type LegalSlug = keyof typeof legalDocuments;
export function legalSnapshot(slug: LegalSlug, extra: string) { const d=legalDocuments[slug]; return {documentType:slug,version:LEGAL_VERSION,title:d.title,content:d.body+"\n\nSİPARİŞE ÖZGÜ BİLGİLER\n"+extra,acceptedAt:new Date()}; }
