"use client";
import Link from "next/link";
import {orderTransitions} from "@/lib/order-view";
import {useState,type FormEvent} from "react";
import {useOrders,type Order} from "@/context/OrderContext";
import {money} from "@/lib/store";
export default function AdminOrdersPage(){
 const {orders,error,loaded,refreshOrders,hasMore,loadingMore,loadMoreOrders}=useOrders();const [search,setSearch]=useState(""),[status,setStatus]=useState("");
 const rows=orders.filter(o=>(!status||o.status===status)&&[o.orderNumber,o.customer.fullName,o.customer.phone,o.customer.email].some(s=>s.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR"))));
 return <main className="p-4 sm:p-6"><div className="max-w-6xl mx-auto"><Link href="/admin" className="text-sm underline">← Yönetim paneli</Link><h1 className="text-3xl font-bold my-7">Sipariş yönetimi</h1>{error&&<p role="alert" className="notice error-notice mb-5">{error}</p>}<div className="flex flex-wrap gap-3 mb-5"><input aria-label="Sipariş ara" className="rounded border p-3" placeholder="Sipariş, müşteri, telefon" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Sipariş durumu" className="rounded border p-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tüm durumlar</option>{["Yeni","Hazırlanıyor","Kargoda","Tamamlandı","İptal","İade","Taslak"].map(s=><option key={s}>{s}</option>)}</select><button className="button-dark" onClick={()=>void refreshOrders()}>Yenile</button></div>{!loaded?<p>Yükleniyor…</p>:!rows.length?<p className="catalog-message">Sipariş bulunamadı.</p>:rows.map(o=><OrderCard key={o.id+o.status+o.paymentStatus+o.trackingNumber} order={o} refresh={refreshOrders}/>)}{hasMore&&<button className="button-dark mb-6" disabled={loadingMore} onClick={()=>void loadMoreOrders()}>{loadingMore?"Yükleniyor…":"Önceki siparişleri yükle"}</button>}</div></main>;
}
function OrderCard({order:o,refresh}:{order:Order;refresh:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setMessage("");try{const r=await fetch("/api/orders/"+o.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const d=await r.json();if(!r.ok)throw new Error(d.message);await refresh();setMessage("Sipariş güncellendi.");}catch(e){setMessage(e instanceof Error?e.message:"Kaydedilemedi.");}finally{setBusy(false);}}
 return <article className="form-panel mb-5"><div className="flex flex-wrap justify-between gap-4"><div><h2>{o.orderNumber}</h2><p>{o.customer.fullName} · {o.customer.phone}</p><p className="text-sm text-slate-500 mt-2">{o.customer.email}</p><p className="text-sm mt-2">{o.delivery.address}, {o.delivery.district} / {o.delivery.city}</p></div><strong>{money(o.total)}</strong></div><div className="my-4 border-t pt-4">{o.items.map((i,n)=><p key={n} className="text-sm py-1">{i.name} × {i.quantity} — {money(i.price*i.quantity)}</p>)}</div><p className="text-sm mb-4">Kargo: {money(o.shippingTotal??0)}{!!o.discountTotal&&<> · Kupon {o.couponCode}: −{money(o.discountTotal)}</>}</p>{o.invoice.type==="corporate"&&<p className="text-sm mb-4">Fatura: {o.invoice.companyName} · {o.invoice.taxOffice} / {o.invoice.taxNumber}</p>}{o.returnRequestedAt&&<p className="notice mb-4">İade talebi: {o.returnReason} · {new Date(o.returnRequestedAt).toLocaleString("tr-TR")}</p>}<form onSubmit={save}><fieldset disabled={busy} className="form-grid"><label>Sipariş durumu<select name="status" defaultValue={o.status}>{[o.status,...(orderTransitions[o.status]??[])].map(s=><option key={s}>{s}</option>)}</select></label><label>Havale / EFT<select name="paymentStatus" defaultValue={o.paymentStatus??"pending"}><option value="pending">Ödeme bekleniyor</option><option value="paid">Tahsilat onaylandı</option><option value="refunded">Geri ödeme yapıldı</option></select></label><label>Kargo firması<input name="shippingCompany" maxLength={100} defaultValue={o.shippingCompany??""}/></label><label>Takip numarası<input name="trackingNumber" maxLength={100} defaultValue={o.trackingNumber??""}/></label><label className="full-width">Takip bağlantısı (https)<input name="trackingUrl" type="url" maxLength={1000} defaultValue={o.trackingUrl??""}/></label><label className="full-width">İade nedeni / açıklaması<textarea name="returnReason" maxLength={2000} defaultValue={o.returnReason??""}/></label><button className="button-dark">{busy?"Kaydediliyor…":"Siparişi güncelle"}</button></fieldset></form><p className="text-xs text-slate-500 mt-3">Tahsilat ve geri ödeme durumunu banka hareketini kontrol ettikten sonra kaydedin.</p>{message&&<p role="status" className="notice mt-3">{message}</p>}</article>;
}
