"use client";
import {useEffect,useMemo,useState} from "react";

type Sub={
 id:string;customerName:string;customerPhone:string;customerEmail:string|null;status:string;frequency:string;intervalCount:number;remainingRuns:number|null;nextRunAt:string;paymentMethod:string;createdAt:string;
 items:Array<{id:string;productName:string;quantity:number;unitPrice:number}>;
};

const statusLabel:Record<string,string>={active:"Aktif",paused:"Durduruldu",cancelled:"İptal",completed:"Tamamlandı"};

export default function SubscriptionsAdmin(){
 const [rows,setRows]=useState<Sub[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/subscriptions",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message||"Abonelikler alınamadı.");setRows(d.subscriptions||[]);}
 useEffect(()=>{void load().catch(e=>setMessage(e.message));},[]);
 const filtered=useMemo(()=>rows.filter(s=>(!status||s.status===status)&&[s.id,s.customerName,s.customerPhone,s.customerEmail||"",...s.items.map(i=>i.productName)].some(v=>v.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR")))),[rows,search,status]);
 async function change(id:string,action:"pause"|"resume"|"cancel"){setBusy(id);setMessage("");try{const r=await fetch("/api/subscriptions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});const d=await r.json();if(!r.ok)throw new Error(d.message);await load();}catch(e){setMessage(e instanceof Error?e.message:"İşlem başarısız.");}finally{setBusy("");}}
 return <main className="p-4 sm:p-7"><div className="max-w-7xl mx-auto">
  <div className="flex flex-wrap items-end justify-between gap-4 mb-7"><div><p className="text-xs text-slate-500">Siparişler / Abonelikler</p><h1 className="text-3xl font-black mt-1">Abonelik Yönetimi</h1><p className="text-sm text-slate-500 mt-2">Tekrarlayan sipariş planlarını, ödeme yöntemini ve sonraki sipariş tarihini yönetin.</p></div><div className="flex gap-2"><button className="button-dark" onClick={async()=>{setMessage("");try{const r=await fetch("/api/subscriptions/run",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessage(String(d.processed)+" abonelik kontrol edildi; "+String(d.results.filter((x:{ok:boolean;orderId?:string})=>x.ok&&!!x.orderId).length)+" sipariş oluşturuldu.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Abonelikler çalıştırılamadı.");}}}>Vadesi gelenleri çalıştır</button><button className="button-dark" onClick={()=>void load()}>Yenile</button></div></div>
  {message&&<p className="notice error-notice mb-4">{message}</p>}
  <div className="form-panel mb-5 flex flex-wrap gap-3"><input className="rounded border p-3 min-w-64" placeholder="Müşteri, telefon, ürün veya ID ara" value={search} onChange={e=>setSearch(e.target.value)}/><select className="rounded border p-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tüm durumlar</option><option value="active">Aktif</option><option value="paused">Durduruldu</option><option value="cancelled">İptal</option><option value="completed">Tamamlandı</option></select></div>
  <div className="overflow-x-auto bg-white border rounded-xl"><table className="w-full text-sm min-w-[980px]"><thead><tr className="bg-slate-50 text-left"><th className="p-3">Abonelik</th><th className="p-3">Müşteri</th><th className="p-3">Ürünler</th><th className="p-3">Periyot</th><th className="p-3">Sonraki Sipariş</th><th className="p-3">Ödeme</th><th className="p-3">Durum</th><th className="p-3">İşlem</th></tr></thead><tbody>
   {filtered.map(s=><tr key={s.id} className="border-t align-top"><td className="p-3"><b>{s.id.slice(-8).toUpperCase()}</b><div className="text-xs text-slate-500 mt-1">{new Date(s.createdAt).toLocaleDateString("tr-TR")}</div></td><td className="p-3"><b>{s.customerName}</b><div>{s.customerPhone}</div><div className="text-xs text-slate-500">{s.customerEmail}</div></td><td className="p-3">{s.items.map(i=><div key={i.id}>{i.productName} × {i.quantity}</div>)}</td><td className="p-3">Her {s.intervalCount} {s.frequency==="weekly"?"hafta":"ay"}<div className="text-xs text-slate-500">{s.remainingRuns==null?"Süresiz":s.remainingRuns+" tekrar kaldı"}</div></td><td className="p-3">{new Date(s.nextRunAt).toLocaleString("tr-TR")}</td><td className="p-3">{s.paymentMethod==="sipay"?"Kart / Sipay":"Havale / EFT"}</td><td className="p-3"><b>{statusLabel[s.status]||s.status}</b></td><td className="p-3"><div className="flex gap-2 flex-wrap">{s.status==="active"&&<button disabled={busy===s.id} className="border rounded px-3 py-2" onClick={()=>void change(s.id,"pause")}>Durdur</button>}{s.status==="paused"&&<button disabled={busy===s.id} className="border rounded px-3 py-2" onClick={()=>void change(s.id,"resume")}>Başlat</button>}{!["cancelled","completed"].includes(s.status)&&<button disabled={busy===s.id} className="border rounded px-3 py-2" onClick={()=>void change(s.id,"cancel")}>İptal</button>}</div></td></tr>)}
  </tbody></table>{!filtered.length&&<p className="p-8 text-center text-slate-500">Abonelik bulunamadı.</p>}</div>
 </div></main>;
}
