"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import DesignEditor from "./DesignEditor";
import {useEffect,useState} from "react";
type AnyMap=Record<string,any>;
const sections={
 firm:{title:"Firma Tanımları",desc:"Firma, iletişim, adres ve vergi bilgileri."},
 legal:{title:"Yasal Sözleşmeler",desc:"Üyelik, satış, ön bilgilendirme ve iade metinleri."},
 design:{title:"Tasarım Ayarları",desc:"Mağaza görünümü ve ürün listeleme tercihleri."},
 users:{title:"Kullanıcılar",desc:"Yönetim paneli kullanıcı kayıtları."},
 files:{title:"Dosya Yönetimi",desc:"Mağazada kullanılan dosya bağlantıları."}
};
export default function AdvancedSettings({section}:{section:keyof typeof sections}){
 const router=useRouter();
 const [uploadBusy,setUploadBusy]=useState(false);
 const [data,setData]=useState<AnyMap|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{fetch("/api/admin-panel-settings",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message||"Ayarlar yüklenemedi.");return d;}).then(d=>setData(d.settings)).catch(()=>setMsg("Ayarlar yüklenemedi."))},[]);
 async function save(next=data){if(!next||busy||uploadBusy)return;setBusy(true);setMsg("");try{const r=await fetch("/api/admin-panel-settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({[section]:next[section]})});const j=await r.json();if(!r.ok)throw Error(j.message);setData(j.settings);setMsg(j.message);router.refresh()}catch(e){setMsg(e instanceof Error?e.message:"Kaydedilemedi.")}finally{setBusy(false)}}
 if(!data)return <main className="p-6" role="status">{msg||"Yükleniyor..."}</main>;
 const meta=sections[section];
 return <main className="max-w-6xl mx-auto p-4 sm:p-8"><Link href="/admin/ayarlar" className="text-sm text-slate-500">‹ Genel Ayarlar</Link><h1 className="text-3xl font-black mt-4">{meta.title}</h1><p className="text-slate-500 mt-2 mb-6">{meta.desc}</p>{msg&&<p className="notice mb-5">{msg}</p>}{section==="firm"&&<Firm value={data.firm} change={(v:any)=>setData({...data,firm:v})}/>} {section==="legal"&&<Legal value={data.legal} change={(v:any)=>setData({...data,legal:v})}/>} {section==="design"&&<DesignEditor value={data.design} change={v=>setData({...data,design:v})} uploading={setUploadBusy}/>} {section==="users"&&<Users value={data.users} change={(v:any)=>setData({...data,users:v})}/>} {section==="files"&&<Files value={data.files} change={(v:any)=>setData({...data,files:v})}/>}<button className="button-dark mt-6" disabled={busy||uploadBusy} onClick={()=>void save()}>{busy?"Kaydediliyor...":"Değişiklikleri kaydet"}</button></main>
}function Firm({value,change}:{value:AnyMap;change:(v:AnyMap)=>void}){const fields=[["name","Firma Adı"],["legalName","Firma Resmi Adı"],["website","Firma İnternet Sitesi"],["authorized","Yetkili Kişi"],["phone","Firma Telefon Numarası"],["phone2","Firma Telefon Numarası 2"],["country","Ülke"],["city","Şehir"],["district","İlçe"],["postalCode","Posta Kodu"],["address","Firma Açık Adresi"],["email","E-posta Adresi"],["orderEmail","Sipariş E-posta Adresi"],["taxOffice","Vergi Dairesi"],["taxNumber","Vergi Numarası"],["kep","KEP Adresi"]];return <section className="form-panel"><div className="form-grid">{fields.map(([k,l])=><label key={k} className={k==="address"?"full-width":""}>{l}{k==="address"?<textarea rows={3} value={value[k]||""} onChange={e=>change({...value,[k]:e.target.value})}/>:<input value={value[k]||""} onChange={e=>change({...value,[k]:e.target.value})}/>}</label>)}</div></section>}
function Legal({value,change}:{value:AnyMap;change:(v:AnyMap)=>void}){const fields=[["membership","Üyelik Sözleşmesi"],["communication","İletişim / Gizlilik Metni"],["distanceSales","Mesafeli Satış Sözleşmesi"],["preInformation","Ön Bilgilendirme Formu"],["returns","Tüketici Hakları – Cayma – İptal İade Koşulları"]];return <div className="space-y-5">{fields.map(([k,l])=><section className="form-panel" key={k}><label className="font-semibold">{l}<textarea className="mt-3 min-h-64" value={value[k]||""} onChange={e=>change({...value,[k]:e.target.value})}/></label></section>)}</div>}
function Users({value,change}:{value:AnyMap[];change:(v:AnyMap[])=>void}){function add(){change([...value,{id:crypto.randomUUID(),username:"",role:"Personel",email:"",active:true}])}return <section className="form-panel"><button type="button" className="button-dark mb-5" onClick={add}>+ Kullanıcı Ekle</button><div className="space-y-3">{value.map((u,i)=><div key={u.id} className="grid md:grid-cols-5 gap-3 border-b pb-3"><input placeholder="Kullanıcı adı" value={u.username} onChange={e=>change(value.map((x,j)=>j===i?{...x,username:e.target.value}:x))}/><input placeholder="E-posta" value={u.email} onChange={e=>change(value.map((x,j)=>j===i?{...x,email:e.target.value}:x))}/><select value={u.role} onChange={e=>change(value.map((x,j)=>j===i?{...x,role:e.target.value}:x))}><option>Admin</option><option>Yönetici</option><option>Personel</option></select><select value={String(u.active)} onChange={e=>change(value.map((x,j)=>j===i?{...x,active:e.target.value==="true"}:x))}><option value="true">Aktif</option><option value="false">Pasif</option></select><button type="button" className="underline" onClick={()=>change(value.filter((_,j)=>j!==i))}>Sil</button></div>)}</div></section>}
function Files({value,change}:{value:AnyMap[];change:(v:AnyMap[])=>void}){function add(){change([...value,{name:"",url:""}])}return <section className="form-panel"><p className="text-sm text-slate-500 mb-4">Logo, katalog, sözleşme veya diğer dosyaların güvenli bağlantılarını burada yönetin.</p><button type="button" className="button-dark mb-5" onClick={add}>+ Dosya Bağlantısı Ekle</button>{value.map((f,i)=><div key={i} className="grid md:grid-cols-[1fr_2fr_auto] gap-3 mb-3"><input placeholder="Dosya adı" value={f.name} onChange={e=>change(value.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input placeholder="https://..." value={f.url} onChange={e=>change(value.map((x,j)=>j===i?{...x,url:e.target.value}:x))}/><button type="button" className="underline" onClick={()=>change(value.filter((_,j)=>j!==i))}>Sil</button></div>)}</section>}