"use client";
import {FormEvent,useEffect,useState} from "react";
type Values=Record<string,string>;
const banks=["BonusCard","Axess","Maximum Kart","CardFinans","Halkbank - Paraf","WorldCard","Kuveyt Türk Kredi Kartı","Bankkart Combo"];
export default function PaymentPosSettings(){
 const [enabled,setEnabled]=useState(false),[configured,setConfigured]=useState<string[]>([]),[values,setValues]=useState<Values>({merchantId:"",merchantKey:"",apiKey:"",merchantSecret:"",environment:"Canlı",securityType:"Standart 3D"}),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{fetch("/api/integrations",{cache:"no-store"}).then(r=>r.json()).then(d=>{const x=(d.integrations||[]).find((i:any)=>i.slug==="sipay");if(x){setEnabled(x.enabled);setConfigured(x.configured||[])}}).catch(()=>{})},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMsg("");try{const r=await fetch("/api/integrations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug:"sipay",enabled,values})});const j=await r.json();if(!r.ok)throw Error(j.message);setConfigured(j.configured||[]);setValues(v=>({...v,merchantKey:"",apiKey:"",merchantSecret:""}));setMsg("Sipay POS ayarları kaydedildi.")}catch(e){setMsg(e instanceof Error?e.message:"Kaydedilemedi.")}finally{setBusy(false)}}
 const secret=(key:string,label:string)=><label>{label}<input type="password" autoComplete="new-password" value={values[key]} placeholder={configured.includes(key)?"Kayıtlı ••••••••":""} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>;
 return <section className="form-panel mt-6"><h2 className="text-xl font-bold">POS Yönetimi</h2><p className="text-sm text-slate-500 mt-2 mb-5">Bir ödeme sağlayıcıyı aktif etmeden önce sağlayıcıdan kurulum bilgilerinizi alın.</p>{msg&&<p className="notice mb-4">{msg}</p>}<form onSubmit={save}><fieldset disabled={busy} className="form-grid"><label>Ödeme Sistemi<input value="Sipay" disabled/></label><label>Durum<select value={String(enabled)} onChange={e=>setEnabled(e.target.value==="true")}><option value="false">Pasif</option><option value="true">Aktif</option></select></label><label>Mağaza Numarası<input value={values.merchantId} placeholder={configured.includes("merchantId")?"Kayıtlı":""} onChange={e=>setValues({...values,merchantId:e.target.value})}/></label>{secret("merchantKey","Mağaza Anahtarı")}{secret("apiKey","API Key")}{secret("merchantSecret","Merchant Secret")}<label>POS Ortamı<select value={values.environment} onChange={e=>setValues({...values,environment:e.target.value})}><option>Canlı</option><option>Test</option></select></label><label>Güvenlik Tipi<select value={values.securityType} onChange={e=>setValues({...values,securityType:e.target.value})}><option>Standart 3D</option><option>3D Secure</option></select></label><button className="button-dark">{busy?"Kaydediliyor...":"Sipay ayarlarını kaydet"}</button></fieldset></form><h3 className="font-bold mt-8 mb-3">Aktif POS'lar / Kart Programları</h3><div className="border rounded-xl overflow-hidden">{banks.map((b,i)=><details key={b} className="border-b last:border-0"><summary className="p-4 cursor-pointer font-medium">{b} <span className="text-slate-400 text-xs ml-2">Sipay</span>{i===banks.length-1&&<span className="float-right text-xs">Ana Pos</span>}</summary><div className="p-4 bg-slate-50 grid sm:grid-cols-2 gap-4"><label>Birincil Pos<select defaultValue={i===banks.length-1?"Evet":"Hayır"}><option>Hayır</option><option>Evet</option></select></label><label>Minimum Taksit Tutarı<input type="number" min="0" step="0.01" defaultValue={i===0?1:0}/></label><div className="full-width"><p className="text-sm mb-2">Taksit Oranları</p><div className="grid grid-cols-6 gap-2">{Array.from({length:18},(_,n)=><label key={n} className="text-xs">{n+1}<input type="number" min="0" step="0.01" placeholder="-" /></label>)}</div></div></div></details>)}</div><details className="mt-6 border rounded-xl"><summary className="p-4 cursor-pointer font-medium">Havale ve EFT</summary><p className="p-4 text-sm text-slate-500">Havale / EFT hesap bilgileri bu sayfanın üst bölümünden yönetilir.</p></details></section>;
}