"use client";
import Link from "next/link";
import {useEffect,useState,type FormEvent} from "react";
type Settings={siteTitle:string;siteDescription:string;keywords:string;geoContent:string;smtpHost:string;smtpPort:number;smtpUser:string;smtpPassword:string;smtpFrom:string;smtpEnabled:boolean;publicUrl:string;hasSmtpPassword:boolean};
const areas=[
 ["Firma Tanımları","Firma, adres, iletişim ve vergi bilgileri.","/admin/ayarlar/firma","🏢"],
 ["Kullanıcılar","Yönetim kullanıcı kayıtlarını yönetin.","/admin/kullanicilar","👤"],
 ["Dosya Yönetimi","Logo, katalog ve dosya bağlantılarını yönetin.","/admin/dosya-yonetimi","📁"],
 ["Tasarım Ayarları","Tema ve mağaza görünüm tercihleri.","/admin/tasarim-ayarlari","🎨"],
 ["Yasal Sözleşmeler","Üyelik, satış ve iade metinlerini yönetin.","/admin/yasal-sozlesmeler","📄"],
 ["Ödeme Ayarları","Havale / EFT, hesap sahibi ve IBAN bilgileri.","/admin/odeme-ayarlari","₺"],
 ["Kargo Ayarları","Kargo ücreti ve ücretsiz kargo alt limiti.","/admin/kargo-ayarlari","↗"],
 ["SEO ve GEO Ayarları","Arama sonuçları ve yapay zekâ araçları için mağaza içerikleri.","/admin/ayarlar/seo","◇"],
 ["E-posta Ayarları","SMTP bağlantısı ve şifre sıfırlama e-postaları.","/admin/mail-sms","✉"],
 ["Güvenlik Ayarları","Müşteri oturumları ve hesap koruması.","/admin/guvenlik","✓"],
 ["Üye / Bayi Grupları","Üyelik grupları, bayi tipleri ve iskontolar.","/admin/uye-gruplari","♧"],
];
export default function SiteSettings({section}:{section:"home"|"seo"|"mail"|"security"}){
 const [settings,setSettings]=useState<Settings|null>(null),[sessions,setSessions]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[loaded,setLoaded]=useState(false);
 useEffect(()=>{if(section==="home")return;const controller=new AbortController();fetch("/api/site-settings",{cache:"no-store",signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);setSettings(d.settings);setSessions(d.activeSessions);setLoaded(true);}).catch(e=>{if(!controller.signal.aborted){setMessage(e.message);setLoaded(true);}});return()=>controller.abort();},[section]);
 async function action(type:string,e?:FormEvent){e?.preventDefault();if(busy||!settings)return;if(type==="revokeSessions"&&!window.confirm("Tüm müşteriler ve bayiler cihazlarında yeniden giriş yapmak zorunda kalacak. Devam edilsin mi?"))return;setBusy(true);setMessage("");try{
  const body=type==="seo"?{action:type,siteTitle:settings.siteTitle,siteDescription:settings.siteDescription,keywords:settings.keywords,geoContent:settings.geoContent}:type==="mail"?{action:type,smtpHost:settings.smtpHost,smtpPort:settings.smtpPort,smtpUser:settings.smtpUser,smtpPassword:settings.smtpPassword,smtpFrom:settings.smtpFrom,smtpEnabled:settings.smtpEnabled,publicUrl:settings.publicUrl}:{action:type,confirm:true};
  const r=await fetch("/api/site-settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message);if(d.settings)setSettings(d.settings);if(d.activeSessions!==undefined)setSessions(d.activeSessions);setMessage(d.message);
 }catch(e){setMessage(e instanceof Error?e.message:"İşlem tamamlanamadı.");}finally{setBusy(false);}}
 const title={home:"Genel Ayarlar",seo:"SEO ve GEO Ayarları",mail:"E-posta Ayarları",security:"Güvenlik Ayarları"}[section];
 return <main className="max-w-6xl mx-auto p-4 sm:p-8">{section!=="home"&&<Link href="/admin/ayarlar" className="text-sm text-slate-500 inline-block mb-6">‹ Genel Ayarlar</Link>}<h1 className="text-2xl font-semibold mb-7">{title}</h1>{message&&<p className="notice mb-5" role="status">{message}</p>}{section==="home"?<div className="akn-panel p-5 sm:p-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{areas.map(([label,description,href,icon])=><Link key={href} href={href} className="flex gap-4 p-5 rounded-xl border border-transparent hover:border-red-100 hover:bg-red-50"><span aria-hidden="true" className="rounded-full bg-red-50 text-red-600 w-11 h-11 flex-shrink-0 grid place-items-center text-xl">{icon}</span><div><h2 className="font-semibold text-sm">{label}</h2><p className="text-sm text-slate-500 mt-2 leading-6">{description}</p></div></Link>)}</div>:!loaded?<p>Yükleniyor…</p>:!settings?<p>Ayarlar alınamadı. Sayfayı yenileyerek tekrar deneyin.</p>:section==="security"?<div className="space-y-6 max-w-3xl"><section className="form-panel"><h2>Hesap koruması</h2><ul className="list-disc pl-5 text-sm leading-8 mt-4"><li>Şifreler salt eklenerek scrypt ile hash olarak saklanır.</li><li>5 hatalı giriş denemesinde hesap 15 dakika kilitlenir.</li><li>Şifre sıfırlama bağlantıları 15 dakika geçerlidir ve tek kullanımlıktır.</li><li>Şifre sıfırlanınca müşterinin tüm oturumları kapatılır.</li><li>İki adımlı doğrulama henüz etkin değildir.</li></ul><Link href="/admin/mail-sms" className="inline-block underline mt-4 text-sm">Şifre sıfırlama e-postalarını yapılandır</Link></section><section className="form-panel"><h2>Müşteri oturumlarını sonlandır</h2><p className="text-sm text-slate-500 my-4">{sessions} süresi dolmamış müşteri oturumu bulunuyor. Bu işlem tüm müşteriler ve bayiler için yeniden giriş gerektirir. Yönetici oturumunu etkilemez.</p><button className="button-red" disabled={busy} onClick={()=>void action("revokeSessions")}>{busy?"İşlem yapılıyor…":"Müşteri oturumlarını kapat"}</button></section></div>:<form className="form-panel max-w-4xl" onSubmit={e=>void action(section,e)}><fieldset disabled={busy} className="form-grid">{section==="seo"?<>
 <label className="full-width">Site başlığı<input required maxLength={120} value={settings.siteTitle} onChange={e=>setSettings({...settings,siteTitle:e.target.value})}/></label>
 <label className="full-width">Arama sonucu açıklaması<textarea required minLength={10} maxLength={500} value={settings.siteDescription} onChange={e=>setSettings({...settings,siteDescription:e.target.value})}/></label>
 <label className="full-width">Anahtar kelimeler (virgülle ayırın)<input maxLength={500} value={settings.keywords} onChange={e=>setSettings({...settings,keywords:e.target.value})}/></label>
 <label className="full-width">Yapay zekâ araçları için mağaza bilgisi / GEO içeriği<textarea rows={8} maxLength={10000} placeholder="Mağazanızı, ürün gruplarınızı, hizmetlerinizi ve sık sorulan soruların cevaplarını yazın." value={settings.geoContent} onChange={e=>setSettings({...settings,geoContent:e.target.value})}/></label>
 <p className="full-width text-sm text-slate-500">Başlık ve açıklama mağazanın meta etiketlerinde kullanılır. GEO içeriği /llms.txt adresinde yayımlanır. Bu alan içerik düzenleyicisidir; otomatik yapay zekâ üretimi yapmaz ve arama sıralaması garantisi vermez.</p>
 </>:<>
 <label>SMTP sunucusu<input autoComplete="off" value={settings.smtpHost} maxLength={253} onChange={e=>setSettings({...settings,smtpHost:e.target.value})}/></label>
 <label>Güvenli bağlantı<select value={settings.smtpPort} onChange={e=>setSettings({...settings,smtpPort:Number(e.target.value)})}><option value={587}>587 — STARTTLS</option><option value={465}>465 — TLS</option></select></label>
 <label>SMTP kullanıcı adı<input autoComplete="off" maxLength={200} value={settings.smtpUser} onChange={e=>setSettings({...settings,smtpUser:e.target.value})}/></label>
 <label>SMTP şifresi<input type="password" autoComplete="new-password" maxLength={500} value={settings.smtpPassword} placeholder={settings.hasSmtpPassword?"Kayıtlı şifreyi korumak için boş bırakın":""} onChange={e=>setSettings({...settings,smtpPassword:e.target.value})}/></label>
 <label>Gönderen e-posta<input type="email" maxLength={200} value={settings.smtpFrom} onChange={e=>setSettings({...settings,smtpFrom:e.target.value})}/></label>
 <label>Canlı site adresi<input type="url" placeholder="https://magazaniz.com" maxLength={500} value={settings.publicUrl} onChange={e=>setSettings({...settings,publicUrl:e.target.value})}/></label>
 <label className="full-width flex gap-3 items-center"><input type="checkbox" className="!w-auto" checked={settings.smtpEnabled} onChange={e=>setSettings({...settings,smtpEnabled:e.target.checked})}/>Şifre sıfırlama e-postalarını etkinleştir</label>
 <p className="full-width text-sm text-slate-500">Sağlayıcınızın SMTP bilgilerini girin. Şifre sunucuda şifrelenerek saklanır ve tekrar gösterilmez. Önce kaydedin, sonra bağlantıyı doğrulayın.</p>
 </>}<button className="button-dark">{busy?"Kaydediliyor…":"Ayarları kaydet"}</button>{section==="mail"&&<button type="button" className="button-red" onClick={()=>void action("verifyMail")}>SMTP bağlantısını doğrula</button>}</fieldset></form>}</main>;
}
