"use client";
import Link from "next/link";
import {useState,type FormEvent} from "react";
import StoreHeader from "@/components/layout/StoreHeader";
import StoreFooter from "@/components/layout/StoreFooter";
import {useOrders,type Order} from "@/context/OrderContext";
import {money} from "@/lib/store";
export default function OrdersPage(){const {orders,error,loaded,refreshOrders,hasMore,loadingMore,loadMoreOrders}=useOrders();return <><StoreHeader/><main className="store-container"><div className="page-heading"><p><Link href="/">Ana sayfa</Link> / Siparişlerim</p><h1>Siparişlerim</h1><p className="mt-3">Hesabınızın ve bu tarayıcıdaki misafir oturumunuzun siparişleri.</p></div>{error?<div className="catalog-message mb-10" role="alert">{error}<button onClick={()=>void refreshOrders()}>Tekrar dene</button></div>:!loaded?<div className="catalog-message mb-10" role="status">Siparişler yükleniyor…</div>:!orders.length?<div className="catalog-message mb-10">Henüz siparişiniz bulunmuyor. <Link href="/urunler" className="underline">Alışverişe başlayın.</Link></div>:<div className="space-y-5 mb-12">{orders.map(o=><OrderCard key={o.id} order={o} refresh={refreshOrders}/>)}</div>}{hasMore&&<button className="button-dark mb-8" disabled={loadingMore} onClick={()=>void loadMoreOrders()}>{loadingMore?"Yükleniyor…":"Önceki siparişleri yükle"}</button>}</main><StoreFooter/></>}
function OrderCard({order:o,refresh}:{order:Order;refresh:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function requestReturn(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setMessage("");try{const r=await fetch("/api/orders/"+o.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"request_return",returnReason:new FormData(e.currentTarget).get("returnReason")})});const d=await r.json();if(!r.ok)throw new Error(d.message);await refresh();setMessage("İade talebiniz alındı.");}catch(e){setMessage(e instanceof Error?e.message:"Talep alınamadı.");}finally{setBusy(false);}}
 async function cancelOrder(){
  if(busy||!window.confirm("Siparişinizi iptal etmek istediğinize emin misiniz?"))return;
  setBusy(true);setMessage("");
  try{const r=await fetch("/api/orders/"+o.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"cancel"})});const d=await r.json();if(!r.ok)throw new Error(d.message);await refresh();setMessage(d.message);}catch(e){setMessage(e instanceof Error?e.message:"İptal işlemi tamamlanamadı.");}finally{setBusy(false);}
 }
 return <article className="form-panel"><div className="flex flex-wrap justify-between gap-4"><div><span className="overline">{new Date(o.createdAt).toLocaleDateString("tr-TR")}</span><h2 className="mt-2">{o.orderNumber}</h2></div><strong className="text-sm">{o.status}</strong></div>{o.items.map((i,n)=><div key={n} className="flex justify-between gap-3 border-t border-slate-100 py-3 text-sm"><span>{i.name} × {i.quantity}</span><strong className="whitespace-nowrap">{money(i.price*i.quantity)}</strong></div>)}<div className="text-sm border-t pt-3"><p>Kargo: {money(o.shippingTotal??0)}</p>{!!o.discountTotal&&<p>Kupon {o.couponCode}: −{money(o.discountTotal)}</p>}</div><div className="flex justify-between mt-5"><span className="text-sm">Kargo dahil toplam</span><strong>{money(o.total)}</strong></div><p className="text-sm mt-3">Havale / EFT: {o.paymentStatus==="paid"?"Ödeme alındı":o.paymentStatus==="refunded"?"Geri ödeme yapıldı":"Ödeme bekleniyor"}</p><p className="text-xs text-slate-500 mt-3">{o.delivery.city} / {o.delivery.district}</p>{o.trackingNumber&&<p className="notice mt-4">{o.shippingCompany} · {o.trackingNumber}{o.trackingUrl?.startsWith("https://")&&<a href={o.trackingUrl} target="_blank" rel="noopener noreferrer" className="underline ml-3">Kargomu takip et ↗</a>}</p>}{["Yeni","Hazırlanıyor"].includes(o.status)&&<button disabled={busy} onClick={()=>void cancelOrder()} className="button-dark mt-5">Siparişi iptal et</button>}{o.status==="İptal"&&o.paymentStatus==="paid"&&<p className="notice mt-4">İptal edildi. Banka geri ödemesi mağaza tarafından ayrıca tamamlanacaktır.</p>}{o.returnRequestedAt?<p className="notice mt-4">İade talebiniz kaydedildi: {o.returnReason}</p>:["Kargoda","Tamamlandı"].includes(o.status)&&<details className="mt-5"><summary className="cursor-pointer font-bold">İade talebi oluştur</summary><form onSubmit={requestReturn} className="form-grid mt-4"><label className="full-width">İade nedeni<textarea name="returnReason" required minLength={5} maxLength={2000}/></label><button disabled={busy} className="button-dark">{busy?"Gönderiliyor…":"Talebi gönder"}</button></form></details>}{message&&<p role="status" className="notice mt-4">{message}</p>}</article>;
}
