"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { integrationItems } from "@/lib/integrations";

export default function IntegrationSettingsPage({params}:{params:Promise<{slug:string}>}){
 const [slug,setSlug]=useState(""); const [enabled,setEnabled]=useState(false); const [values,setValues]=useState<Record<string,string>>({}); const [configured,setConfigured]=useState<string[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{params.then(x=>setSlug(x.slug));},[params]);
 const item=useMemo(()=>integrationItems.find(x=>x.slug===slug),[slug]);
 useEffect(()=>{if(!slug)return;fetch("/api/integrations",{cache:"no-store"}).then(r=>r.json()).then(d=>{const s=d.integrations?.find((x:{slug:string})=>x.slug===slug);if(s){setEnabled(s.enabled);setConfigured(s.configured||[]);}}).catch(()=>{});},[slug]);
 if(!item)return <main className="p-8"><p>Entegrasyon bulunamadı.</p><Link href="/admin/entegrasyonlar">Entegrasyonlara dön</Link></main>;
 if(item.mode==="feed"){const google=slug==="google-merchant";const url=google?"/api/feeds/google":"/api/feeds/meta";return <main className="px-5 py-8 lg:px-8"><div className="mx-auto max-w-4xl"><Back/><h1 className="mt-5 text-3xl font-black">{item.name}</h1><p className="mt-2 text-slate-500">{item.description}</p><section className="mt-7 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-black">Canlı feed adresi</h2><p className="mt-3 break-all rounded-lg bg-slate-50 p-4 text-sm">{url}</p><a href={url} target="_blank" className="mt-4 inline-block rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Feed'i kontrol et ↗</a><p className="mt-4 text-xs text-slate-500">Bu adresi ilgili platformdaki veri kaynağı/feed alanına ekleyin. Ürünler veritabanından otomatik oluşturulur.</p></section></div></main>}
 if(item.mode==="external")return <main className="px-5 py-8 lg:px-8"><div className="mx-auto max-w-4xl"><Back/><h1 className="mt-5 text-3xl font-black">{item.name}</h1><section className="mt-7 rounded-2xl border bg-white p-6"><p className="text-sm text-slate-600">Genel amaçlı API anahtarı üretimi güvenlik nedeniyle otomatik açılmadı. Kullanılacak ERP veya servis belirlendiğinde yalnızca gereken yetkilerle bağlantı oluşturulmalıdır.</p></section></div></main>;
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/integrations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,enabled,values})});const d=await r.json();if(!r.ok)throw new Error(d.message);setConfigured(d.configured||[]);setValues({});setMessage("Ayarlar güvenli şekilde kaydedildi.");}catch(e){setMessage(e instanceof Error?e.message:"Kaydedilemedi.");}finally{setBusy(false);}}
 async function syncErp(){setBusy(true);setMessage("AKN E-Ticaret ve ERP ürünleri senkronize ediliyor…");try{const r=await fetch("/api/integrations/bahadir-erp-v2/sync",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.message||"Senkronizasyon başarısız.");setMessage(`Senkronizasyon tamamlandı. ERP'ye yeni: ${d.pushed}, güncellenen: ${d.updated}, ERP'den alınan: ${d.pulled}, hata: ${d.failed}.`);}catch(e){setMessage(e instanceof Error?e.message:"Senkronizasyon başarısız.");}finally{setBusy(false);}}
 return <main className="px-5 py-8 lg:px-8"><div className="mx-auto max-w-4xl"><Back/><h1 className="mt-5 text-3xl font-black">{item.name}</h1><p className="mt-2 text-slate-500">{item.description}</p><form onSubmit={save} className="mt-7 rounded-2xl border bg-white p-6 shadow-sm"><label className="flex items-center gap-3 font-bold"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Entegrasyonu etkinleştir</label><div className="mt-6 grid gap-5">{item.fields?.map(f=><label key={f.key} className="grid gap-2 text-sm font-bold">{f.label}{configured.includes(f.key)&&<small className="font-normal text-emerald-700">Kayıtlı — değiştirmek istemiyorsanız boş bırakın.</small>}<input className="rounded-xl border border-slate-200 px-4 py-3 font-normal" type={f.secret?"password":"text"} placeholder={f.placeholder||""} value={values[f.key]||""} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))} autoComplete="off"/></label>)}</div>{message&&<p className="mt-5 rounded-lg bg-slate-50 p-3 text-sm">{message}</p>}<div className="mt-6 flex flex-wrap gap-3"><button disabled={busy} className="rounded-xl bg-red-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{busy?"İşleniyor…":"Ayarları Kaydet"}</button>{slug==="bahadir-erp-v2"&&<button type="button" onClick={syncErp} disabled={busy||!enabled} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-50">Ürünleri Şimdi Senkronize Et</button>}</div></form></div></main>
}
function Back(){return <Link href="/admin/entegrasyonlar" className="text-sm font-bold text-slate-600">← Entegrasyon Merkezi</Link>}
