"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {useProducts} from "@/context/ProductContext";
const TABS=["Anasayfa","Popüler","Kategori","Marka","Yeni","Sponsor","İndirimli"];
export default function Vitrin(){
 const {products,loaded,updateProduct}=useProducts(); const [tab,setTab]=useState("Anasayfa"); const [search,setSearch]=useState(""); const [busy,setBusy]=useState("");
 const visible=useMemo(()=>{const q=search.trim().toLocaleLowerCase("tr-TR");return products.filter(p=>(p.showcases||[]).includes(tab)).filter(p=>!q||p.name.toLocaleLowerCase("tr-TR").includes(q)||p.sku.toLocaleLowerCase("tr-TR").includes(q)).sort((a,b)=>Number(a.showcaseOrder?.[tab]??999999)-Number(b.showcaseOrder?.[tab]??999999));},[products,search,tab]);
 const candidates=useMemo(()=>products.filter(p=>!(p.showcases||[]).includes(tab)),[products,tab]);
 async function order(items:typeof visible){for(let i=0;i<items.length;i++){const p=items[i];await updateProduct(p.id,{showcaseOrder:{...(p.showcaseOrder||{}),[tab]:i+1}})}}
 async function move(id:string,d:-1|1){const i=visible.findIndex(p=>p.id===id),to=i+d;if(i<0||to<0||to>=visible.length)return;const next=[...visible];[next[i],next[to]]=[next[to],next[i]];setBusy(id);await order(next);setBusy("");}
 async function remove(id:string){const p=products.find(x=>x.id===id);if(!p)return;setBusy(id);await updateProduct(id,{showcases:(p.showcases||[]).filter(x=>x!==tab),showcaseOrder:Object.fromEntries(Object.entries(p.showcaseOrder||{}).filter(([k])=>k!==tab))});setBusy("");}
 async function add(id:string){const p=products.find(x=>x.id===id);if(!p)return;setBusy(id);await updateProduct(id,{showcases:[...new Set([...(p.showcases||[]),tab])],showcaseOrder:{...(p.showcaseOrder||{}),[tab]:visible.length+1}});setBusy("");}
 return <main className="min-h-screen bg-slate-100 px-4 py-8 text-slate-900 lg:px-8"><div className="mx-auto max-w-[1500px]">
  <Link href="/admin/urunler" className="text-sm font-bold text-slate-500">← Ürünler</Link><h1 className="mt-2 text-3xl font-black">Vitrin Düzeni</h1><p className="mb-6 mt-1 text-sm text-slate-500">Mağazada ürünlerin hangi vitrinde ve hangi sırada görüneceğini yönetin.</p>
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">
   <div className="flex gap-1 overflow-x-auto border-b px-4 pt-3">{TABS.map(x=><button key={x} type="button" onClick={()=>setTab(x)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-bold ${tab===x?"border-indigo-600 text-indigo-700":"border-transparent text-slate-500"}`}>{x}</button>)}</div>
   <div className="flex flex-col gap-3 border-b p-4 lg:flex-row lg:items-center lg:justify-between"><div className="text-sm"><strong>{visible.length}</strong> ürün</div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ürün adı veya stok kodu ara..." className="w-full rounded-xl border px-4 py-2.5 lg:max-w-md"/></div>
   {!loaded?<div className="p-10 text-center font-bold">Yükleniyor...</div>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Sıra</th><th className="px-4 py-3">Ürün</th><th className="px-4 py-3">Marka</th><th className="px-4 py-3">Kategori</th><th className="px-4 py-3">Stok</th><th className="px-4 py-3 text-right">İşlem</th></tr></thead><tbody className="divide-y">
    {visible.map((p,i)=><tr key={p.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-black">{i+1}</td><td className="px-4 py-3"><Link href={`/admin/urunler/${p.id}/duzenle`} className="flex items-center gap-3 font-bold hover:text-indigo-700"><span className="flex h-11 w-11 items-center justify-center overflow-hidden rounded-lg border bg-white">{p.image?<img src={p.image} alt="" className="h-full w-full object-contain"/>:"AKN"}</span><span><span className="block max-w-md truncate">{p.name}</span><small className="font-medium text-slate-400">{p.sku}</small></span></Link></td><td className="px-4 py-3">{p.brand}</td><td className="px-4 py-3">{p.category}</td><td className="px-4 py-3">{p.stock}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><button disabled={i===0||busy===p.id} onClick={()=>move(p.id,-1)} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-30">↑</button><button disabled={i===visible.length-1||busy===p.id} onClick={()=>move(p.id,1)} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-30">↓</button><button disabled={busy===p.id} onClick={()=>remove(p.id)} className="rounded-lg border border-red-200 px-3 py-2 font-bold text-red-600">Çıkar</button></div></td></tr>)}
   </tbody></table>{visible.length===0&&<div className="p-10 text-center text-slate-500">Bu vitrinde henüz ürün yok.</div>}</div>}
  </section>
  <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">{tab} vitrinine ürün ekle</h2><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{candidates.slice(0,60).map(p=><button key={p.id} type="button" disabled={busy===p.id} onClick={()=>add(p.id)} className="flex items-center justify-between gap-3 rounded-xl border p-3 text-left hover:border-indigo-300 hover:bg-indigo-50 disabled:opacity-50"><span className="min-w-0"><strong className="block truncate">{p.name}</strong><small className="text-slate-500">{p.sku} · Stok {p.stock}</small></span><span className="rounded-lg bg-slate-900 px-3 py-1.5 text-xs font-bold text-white">Ekle</span></button>)}</div></section>
 </div></main>
}
